Feature/turret fixes
bcit-datacomm/4981_Linux_Game pull request #100
Opened 2017-04-10 20:02 UTC by YiHChen

- Turrets no longer track zombies while being held by a marine
- Turrets no longer rotate while tracking zombies
- Fixed turrets not being able to be picked up after being placed
- Added a firing delay after placing a turret; player can no longer instantly shoot after placing a turret
- Added a texture for the turret
- Turrets size was increased to fit turret texture

2017-04-10 20:07 UTC, JohnAgapeyev requested changes
Why did you split the little if statement?
He was so young and innocent

2017-04-10 20:07 UTC, JohnAgapeyev commented on src/game/GameManager.cpp
> +                if (it->second.isActivated()) {
Why did you split the if statement?
Put it back

2017-04-10 21:07 UTC, JohnAgapeyev approved these changes

2017-04-11 02:27 UTC, isaacmorneau approved these changes

2017-04-11 02:27 UTC, merged