Sprint 3
bcit-datacomm/4981_Linux_Game pull request #14
Opened 2017-03-13 20:51 UTC by jacobmcphail

2017-03-13 21:23 UTC, isaacmorneau commented on src/Barricade.cpp
> +        const float moveX, const float moveY, CollisionHandler  &ch){
whats up with this spacing?

2017-03-13 21:23 UTC, isaacmorneau commented on src/Barricade.cpp
> +   boolPlaceable = false;
spacing

2017-03-13 21:24 UTC, isaacmorneau commented on src/Barricade.cpp
> +    if(this->checkPlaceablePosition(playerX, playerY, moveX, moveY, ch)) {
`this->` is redundant, dont use it

2017-03-13 21:24 UTC, JohnAgapeyev commented on src/Barricade.cpp
> +        boolPlaced(boolPlaced) {
boolPlaceable violates variable naming conventions.
All hungarian notation and variations thereof are forbidden.
Rename variable to isPlaced or something along those lines.
Type should never be part of the variable identifier.

2017-03-13 21:29 UTC, JohnAgapeyev commented on src/Base.cpp
> +    setX((MAP_WIDTH / 2) - BASE_WIDTH/2);
Spacing on the second divide operation

2017-03-13 21:32 UTC, JohnAgapeyev commented on src/CollisionHandler.cpp
> +    for (unsigned int x = 0; x < returnObjects.size(); x++) {
Calling .size() inside of loop condition is unnecessary.
Replace with:
`for (unsigned int x = 0, len = returnObject.size(); x < len; x++) {'
Or something similar

2017-03-13 21:33 UTC, JohnAgapeyev commented on src/CollisionHandler.cpp
> +        if (returnObjects.at(x) != nullptr && hb->attached != returnObjects.at(x)->attached
at() performs runtime bounds checking and throws exception on out-of-bounds.
If this is not the desired behaviour, and if the code doesn't not break when changing it to to operator[], please change.

2017-03-13 21:34 UTC, JohnAgapeyev commented on src/CollisionHandler.cpp
> +    for (unsigned int x = 0; x < returnObjects.size(); x++) {
'.size()' called inside loop
See above comment

2017-03-13 21:35 UTC, JohnAgapeyev commented on src/CollisionHandler.cpp
> +    std::vector<HitBox*> allHitBoxes;
Can be condensed to:
' std::vector<HitBox *> allHitBoxes = quadtreePro.objects; '

2017-03-13 21:37 UTC, JohnAgapeyev commented on src/GameManager.cpp
> +  b.second.texture.render(gRenderer, b.second.getX()-camX, b.second.getY()-camY);
Spacing

2017-03-13 21:39 UTC, JohnAgapeyev commented on src/GameManager.cpp
> +    weaponDropManager.insert({id, newWeaponDrop});
This method of insertion is inconsistent with above inserts.
Is there are reason for the difference?
Which method should be used for inserting into the various manager maps?

2017-03-13 21:41 UTC, JohnAgapeyev commented on src/GameManager.cpp
> + barricadeManager.erase(id);
Spacing

2017-03-13 21:42 UTC, JohnAgapeyev commented on src/GameManager.cpp
> +   } else {
Else is unnecessary due to returning in above if statement
Please remove.

2017-03-13 21:42 UTC, JohnAgapeyev commented on src/GameManager.cpp
> +void GameManager::setBoundary(SDL_Renderer* gRenderer, const float startX, const float startY, const float endX, const float endY){
Line too long
Wrap it up

2017-03-13 21:42 UTC, JohnAgapeyev commented on src/GameManager.cpp
> +    int width = endX - startX + 200;
Needs const

2017-03-13 21:43 UTC, JohnAgapeyev commented on src/GameManager.cpp
> +    int height = 100;
Needs constexpr

2017-03-13 21:44 UTC, isaacmorneau commented on src/CollisionHandler.cpp
> +    for (unsigned int x = 0; x < returnObjects.size(); x++) {
look at the DRY concept in implementation

2017-03-13 21:45 UTC, JohnAgapeyev commented on src/GameManager.cpp
> +    width = 100;
Don't reassign variable when it isn't clear.
Use separate variable for different walls.

2017-03-13 21:45 UTC, JohnAgapeyev commented on src/GameManager.cpp
> +    const float sX = (endX + startX)/2 - BASE_WIDTH - 100;
Spacing on the `/2`

2017-03-13 21:47 UTC, JohnAgapeyev commented on src/GameManager.cpp
> +    spawnPoints.push_back(Point(-900, -900));
Points are just a typedef of std::pair<double, double>, yeah?
This makes redundant copies.
Replace with `spawnPoints.emplace({-900, -900});`
That should work

2017-03-13 21:47 UTC, isaacmorneau commented on src/CollisionHandler.cpp
> +            && SDL_HasIntersection(&hb->getRect(), &returnObjects.at(x)->getRect())
should be one indentation level further as below, see indentation guide

2017-03-13 21:48 UTC, JohnAgapeyev commented on src/GameManager.cpp
> +        for(const auto z : zombieManager) {
Any reason zombies are being copied inside the loop?
Should be capturing z by reference

2017-03-13 21:49 UTC, JohnAgapeyev commented on src/GameManager.cpp
> +            if(count >= spawnPoints.size())
Missing curly braces
Also reuse of spawnPoints.size(), recommend pulling it out into temporary variable to reduce method calls

2017-03-13 21:49 UTC, JohnAgapeyev commented on src/GameManager.cpp
> +            count++;
Use pre-increment unless post is needed

2017-03-13 21:49 UTC, JohnAgapeyev commented on src/GameManager.cpp
> +        for(const auto id : ids) {
capture id by reference

2017-03-13 21:50 UTC, JohnAgapeyev commented on src/GameManager.cpp
> +    for(int i = 0; i < n ; i ++) {
Spacing in the for loop
Also prefer pre-increment

2017-03-13 21:51 UTC, JohnAgapeyev commented on src/GameManager.cpp
> +        for(const auto p : spawnPoints)
Should likely be capturing by reference

2017-03-13 21:53 UTC, JohnAgapeyev commented on src/GameStateMatch.cpp
> +        if(fpsTimer.getTicks() / 1000 > second) {
1000 is a magic number

2017-03-13 21:53 UTC, JohnAgapeyev commented on src/GameStateMatch.cpp
> +    while ( SDL_PollEvent(&event)) {
Remove space after opening parenthesis

2017-03-13 21:55 UTC, JohnAgapeyev commented on src/GameStateMatch.cpp
> +    frameFont = nullptr;
Setting pointer to null inside destructor is pointless as it will be deleted, so no references will exist
Remove line

2017-03-13 21:55 UTC, JohnAgapeyev commented on src/HitBox.cpp
> +void HitBox::move(const float& x, const float& y){
floats should be captured by value, not by reference

2017-03-13 21:55 UTC, JohnAgapeyev commented on src/HitBox.cpp
> +HitBox::HitBox(const float& x, const float& y, SDL_Rect rect, Entity* attached) : attached(attached) {
Floats should not be captured by reference

2017-03-13 21:56 UTC, JohnAgapeyev commented on src/HitBox.cpp
>  void HitBox::setFriendly(bool isFriendly) {
bool should be const

2017-03-13 21:56 UTC, JohnAgapeyev commented on src/Inventory.cpp
>  void Inventory::switchCurrent(int slot){
slot should be const

2017-03-13 21:57 UTC, JohnAgapeyev commented on src/Inventory.cpp
>              int randGun = rand() % 2 + 1;
randgun should be const

2017-03-13 21:58 UTC, JohnAgapeyev commented on src/Object.cpp
>  void Object::setHeight(int h) {
setters should take params by const as a general rule

2017-03-13 21:59 UTC, JohnAgapeyev commented on src/Player.cpp
> +    if (SDL_GetMouseState(NULL, NULL) & SDL_BUTTON(SDL_BUTTON_LEFT)) {
NULL should become nullptr

2017-03-13 22:00 UTC, JohnAgapeyev commented on src/Player.cpp
> +            marine->getY() + distance*sin(angle));
Fix line indentation

2017-03-13 22:00 UTC, JohnAgapeyev commented on src/Player.h
>  #endif
Place newline at end of file

2017-03-13 22:01 UTC, JohnAgapeyev commented on src/Quadtree.cpp
> +    int subWidth = static_cast<int>(bounds.w / 2);
should be const

2017-03-13 22:02 UTC, JohnAgapeyev commented on src/Quadtree.cpp
> +    double verticalMidpoint = bounds.x + (bounds.w / 2);
Should be const

2017-03-13 22:03 UTC, JohnAgapeyev commented on src/Quadtree.cpp
> +    else if (hitRect.x > verticalMidpoint) {
else should be on the same line as the closing if statement brace

2017-03-13 22:03 UTC, JohnAgapeyev commented on src/Quadtree.cpp
> +    objectCounter++;
Use preincrement

2017-03-13 22:03 UTC, JohnAgapeyev commented on src/Quadtree.cpp
> +        int index = getIndex(pRect);
const int index

2017-03-13 22:04 UTC, JohnAgapeyev commented on src/Quadtree.cpp
> +            int index = getIndex(objects.at(i));
Should be const

2017-03-13 22:04 UTC, JohnAgapeyev commented on src/Quadtree.cpp
> +                objects.erase(objects.begin()+i);
Spacing on the addition

2017-03-13 22:04 UTC, JohnAgapeyev commented on src/Quadtree.cpp
> +                i++;
Preincrement

2017-03-13 22:04 UTC, JohnAgapeyev commented on src/Quadtree.cpp
> +    int index = getIndex(pRect);
const needed

2017-03-13 22:06 UTC, JohnAgapeyev commented on src/Turret.cpp
> +    const float distance = sqrt(abs(distanceX+distanceY));
Spacing on the addition

2017-03-13 22:06 UTC, JohnAgapeyev commented on src/Turret.cpp
> +void Turret::move(float playerX, float playerY, float moveX, float moveY, CollisionHandler &ch) {
Params should be const

2017-03-13 22:06 UTC, JohnAgapeyev commented on src/Turret.cpp
> +    if(this->collisionCheckTurret(playerX, playerY, moveX, moveY, ch)) {
Don't dereference this

2017-03-13 22:07 UTC, JohnAgapeyev commented on src/Zombie.cpp
> +    int ty = getY() + 20 * sinVal;
These temp variables should be const

2017-03-13 22:08 UTC, JohnAgapeyev commented on src/weapons/HandGun.h
> +    const int FIRERATE      = 1000;
Why is one variable declared constexpr and the rest declared const?
Make all constexpr

2017-03-13 22:09 UTC, JohnAgapeyev commented on src/weapons/InstantWeapon.cpp
> +     return;
Spacing

2017-03-13 22:09 UTC, JohnAgapeyev commented on src/weapons/InstantWeapon.cpp
> +     return;
Spacing

2017-03-13 22:09 UTC, JohnAgapeyev commented on src/weapons/InstantWeapon.h
> +  int clip, int clipMax, int ammo, int AOE, int reloadSpeed, int fireRate, bool isReadyToFire);
Spacing

2017-03-13 22:09 UTC, JohnAgapeyev commented on src/weapons/InstantWeapon.h
> +    void fire(Marine &marine);
Why is this indented?

2017-03-13 22:10 UTC, JohnAgapeyev commented on src/weapons/Rifle.h
> +    const int AMMO          = 1000;
Needs constexpr on all these

2017-03-13 22:10 UTC, JohnAgapeyev commented on src/weapons/ShotGun.h
> +    const int AMMO          = 1000;
constexpr

2017-03-13 22:10 UTC, JohnAgapeyev commented on src/weapons/Weapon.cpp
> +        } if (ammo < clipMax){
Why is all this code commented out?

2017-03-13 22:11 UTC, JohnAgapeyev commented on src/weapons/Weapon.cpp
> +bool Weapon::reduceAmmo(int rounds){
Needs const

2017-03-13 22:12 UTC, JohnAgapeyev commented on src/weapons/Weapon.cpp
> +int Weapon::getClip(){
getters should have their methods declared const since they don't change internal values

2017-03-13 22:13 UTC, JohnAgapeyev commented on src/weapons/Weapon.cpp
> +int Weapon::getRAOE(){
Getters should be declared as const methods
Preferably put into the header as well

2017-03-13 22:13 UTC, JohnAgapeyev requested changes
Numerous style guide fixed required

2017-03-13 22:37 UTC, isaacmorneau commented on src/HitBox.cpp
> +HitBox::HitBox(const float& x, const float& y, SDL_Rect rect, Entity* attached) : attached(attached) {
primitives in general dont get captured by reference

2017-03-13 22:45 UTC, isaacmorneau commented on src/Player.cpp
>          int distance = 100;
should be const minimum and if it is the default distance it should be in the header as constexpr

2017-03-13 22:45 UTC, isaacmorneau commented on src/Player.cpp
> +            marine->getY() + distance*sin(angle));
and line spacing

2017-03-13 22:46 UTC, isaacmorneau commented on src/Player.cpp
> +       int distance = 100;
should be const

2017-03-13 22:52 UTC, isaacmorneau commented on src/Quadtree.cpp
> +        }
can be made non branching but john wont let me tell you how

2017-03-13 23:03 UTC, isaacmorneau commented on src/Turret.cpp
> +    return (distance <= 200 && !ch.detectMovementCollision(&hitBox));
200 is magic

2017-03-13 23:04 UTC, isaacmorneau commented on src/Turret.cpp
> +    if(this->collisionCheckTurret(playerX, playerY, moveX, moveY, ch)) {
`this->` is always redundant, as it states in the wiki

2017-03-14 06:34 UTC, isaacmorneau commented on src/BasicMedkit.h
> +*/
double comment

2017-03-14 07:11 UTC, isaacmorneau commented on src/GameManager.cpp
> +        for(const auto z : zombieManager) {
`const auto& z`

2017-03-14 07:12 UTC, isaacmorneau commented on src/GameManager.cpp
> +}
four new lines with no readability benefit

2017-03-14 07:16 UTC, isaacmorneau commented on src/GameStateMatch.cpp
> +               switch( event.key.keysym.sym ) {
missing a space to match indentation on `}` `break;` and `switch(...`

2017-03-14 07:33 UTC, isaacmorneau commented on src/weapons/InstantWeapon.h
> +protected:
empty section is redundant

2017-03-14 07:35 UTC, isaacmorneau commented on src/weapons/Weapon.cpp
> +int Weapon::getRAOE(){
non trivial getters should be in the cpp but these are trivial so its simpler to just put them in the header

2017-03-14 07:39 UTC, isaacmorneau requested changes
adjust to comments

2017-03-15 19:18 UTC, isaacmorneau commented on src/basic/Entity.h
> +    int32_t getId()const{return id;}; //returns the id of the entity
spacing

2017-03-15 19:19 UTC, JohnAgapeyev commented on src/basic/Entity.h
> +    void setPosition(float x, float y); // Set marine position
floats should be const

2017-03-15 19:21 UTC, JohnAgapeyev commented on src/buildings/Wall.cpp
> +void Wall::collidingProjectile(int damage) {
const param

2017-03-15 19:29 UTC, JohnAgapeyev commented on src/collision/Quadtree.cpp
> +    nodes[3] = std::make_shared<Quadtree>(level+1, SDL_Rect{x + subWidth, y + subHeight, subWidth, subHeight});
Spacing on the + 1

2017-03-15 19:56 UTC, JohnAgapeyev commented on src/basic/LTimer.h
> +constexpr float TIME_SECOND = 1000;
Make static as well

2017-03-15 19:57 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +        cosVal = cos(getAngle()*PI/180.0);
Spacing on math operations

2017-03-15 19:58 UTC, JohnAgapeyev commented on src/creeps/Zombie.h
> +constexpr int ZOMBIE_WIDTH = 75;
Make static

2017-03-15 20:02 UTC, JohnAgapeyev commented on src/inventory/weapons/HandGun.h
> +    constexpr bool READY        = true;
Assignment should be one space after variable
Don't align values like this

2017-03-15 20:03 UTC, JohnAgapeyev commented on src/inventory/weapons/Rifle.h
> +    constexpr bool READY    = true;
Alignment as mentioned above

2017-03-15 20:05 UTC, JohnAgapeyev commented on src/turrets/Turret.cpp
> +                  const float moveX, const float moveY, CollisionHandler &ch) {
Indentation on wrapped line

2017-03-15 20:06 UTC, JohnAgapeyev commented on src/turrets/Turret.h
> +constexpr int PLACE_DISTANCE = 200;
Make consts static

2017-03-15 20:06 UTC, JohnAgapeyev approved these changes
Review comments

2017-03-15 20:21 UTC, isaacmorneau approved these changes

2017-03-15 20:22 UTC, merged