Getting AI code into main repo
bcit-datacomm/4981_Linux_Game pull request #15
Opened 2017-03-14 20:30 UTC by RobertArendac

2017-03-15 21:27 UTC, isaacmorneau commented on src/buildings/Base.cpp
>      int gab = 100;
this should be constexpr and in the header if its allways the same

2017-03-15 21:28 UTC, isaacmorneau commented on src/buildings/Base.h
>  //TODO :  change later.
TODO's should never exist in the main repo

2017-03-15 21:29 UTC, isaacmorneau commented on src/creeps/Node.h
> +static int my[DIR_CAP]={0, 1, 1, 1, 0, -1, -1, -1};
can be made constexpr

2017-03-15 21:29 UTC, isaacmorneau commented on src/creeps/Node.h
> +    : xPos_(xPos), yPos_(yPos), lv_(lv), pri_(pri) {}
indentation doesnt follow guide

2017-03-15 21:31 UTC, isaacmorneau commented on src/creeps/Zombie.cpp
> +    printf("Create Zombie\n");
please replace all printfs with logv from "../log/log.h"

2017-03-15 21:32 UTC, isaacmorneau commented on src/creeps/Zombie.cpp
> +void Zombie::setStep(const int sp) {
simple setters and getters can be in the header

2017-03-15 21:32 UTC, isaacmorneau commented on src/creeps/Zombie.cpp
> +}
all above simple getters and setters should be moved to the header

2017-03-15 21:36 UTC, isaacmorneau commented on src/creeps/Zombie.cpp
> +bool Zombie::overlapped(const float x1, const float y1,
all collisions without exception should use the collision handlers as they use quadtrees

2017-03-15 21:37 UTC, isaacmorneau commented on src/creeps/Zombie.cpp
> +                        const float overlap) {
even so, spacing does not follow guide

2017-03-15 21:42 UTC, RobertArendac commented on src/buildings/Base.cpp
>      int gab = 100;
FYI I'm pretty sure my team didn't write this but I'll fix it

2017-03-15 22:40 UTC, JohnAgapeyev commented on src/buildings/Base.cpp
>                                                         getX() + getWidth() + gab));
Fix indentation on wrapped line

2017-03-15 22:41 UTC, JohnAgapeyev commented on src/creeps/Node.h
> +    int yPos_;
Don't use underscores on private member identifiers

2017-03-15 22:42 UTC, JohnAgapeyev commented on src/creeps/Node.h
> +         lv_ += (dir%2 ==0 ? BASE_COST : EXTEND_COST);
Fix spacing on the % operator

2017-03-15 22:44 UTC, JohnAgapeyev commented on src/buildings/Base.cpp
> +                                                       getX() + getWidth() + GAP));
Fix indentation

2017-03-15 22:44 UTC, RobertArendac commented
So I think I handled all the PR review comments, but pathfinding is completely screwed up now with the walls so I don't know if you want to hold off on merging.

2017-03-15 22:45 UTC, JohnAgapeyev commented on src/creeps/Node.h
> +    virtual ~Node() {}
Mark empty destructor as default

2017-03-15 22:45 UTC, JohnAgapeyev commented on src/creeps/Node.h
> +    int getPriority() const {
Trivial getters and setters should be moved into the header

2017-03-15 22:47 UTC, JohnAgapeyev commented on src/creeps/Node.h
> +        static int xDist, yDist, dist;
These variables should not be static.
They are not thread-safe, and are being reassigned every time the method is called.
Use local temp variables here

2017-03-15 22:49 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +    int sp = getStep();
sp should be const

2017-03-15 22:49 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +    string pth = getPath();
const

2017-03-15 22:50 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +    return (sp < (int) pth.length() ? stoi(pth.substr(sp,1)) : -1);
Use static cast instead of c-style cast

2017-03-15 22:51 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +    float startY = getY();
These vars should be const

2017-03-15 22:51 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +            frame--;
Prefer preincrement

2017-03-15 22:52 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +        frame--;
Use preincrement

2017-03-15 22:54 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +                            const float xDest, const float yDest) {
Fix indentation

2017-03-15 22:58 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +    int index = 0;
This should be const

2017-03-15 22:59 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +            openNodes[i][j] = 0;
These can be changed to memset 0

2017-03-15 23:00 UTC, JohnAgapeyev commented on src/creeps/Node.h
> +static constexpr int MY[DIR_CAP]={0, 1, 1, 1, 0, -1, -1, -1};
Use std array over c-style arrays

2017-03-15 23:16 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +    int yNodeDest = (int) yDest / TILE_SIZE;
Use static_cast instead of c-style casting

2017-03-15 23:17 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +                           pq[index].top().getLevel(), pq[index].top().getPriority());
I'd recommend making a temporary variable that is equal to `pq[index].top` to eliminate these repeated calls and make things look cleaner

2017-03-15 23:18 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +                c = '0' + (j + DIR_CAP/2)%DIR_CAP;
Spacing

2017-03-15 23:21 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +            while (!pq[index].empty()) {
This can be changed into something cleaner
Use `pq[index] = std::priorityQueue<Node()`

2017-03-15 23:21 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +                || gameMap[xdx][ydy] == 1 || closedNodes[xdx][ydy] == 1)) {
Indent level one more time to keep it out of line with code below the wrapped line

2017-03-15 23:29 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +            while (!pq[index].empty()) {
Sorry, could you explain this a bit more? Cleaner how?

2017-03-15 23:37 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +    int index = 0;
Making it const breaks it

2017-03-15 23:49 UTC, JohnAgapeyev commented on src/creeps/Zombie.h
> +static constexpr int NORTHWEST = 315;
For constants like this with a finite number of values that are all related, use an enum class
Unless you want the possibility of comparing an x position to NORTHWEST
Enum class is better readability and enforces scoping on comparisons, preventing the above issue

2017-03-15 23:52 UTC, JohnAgapeyev commented on src/game/GameManager.cpp
> +	for (auto& t : turretManager) {
TABS

2017-03-15 23:53 UTC, JohnAgapeyev commented on src/game/GameManager.cpp
> +const std::map<int32_t, Zombie>& GameManager::getZombies() {
Move to header

2017-03-15 23:53 UTC, JohnAgapeyev commented on src/game/GameStateMatch.cpp
> +	GameManager::instance()->updateTurrets(delta);
Filthy tabber

2017-03-15 23:54 UTC, JohnAgapeyev commented on src/turrets/Turret.cpp
> +    {
Bracket on same line as if

2017-03-15 23:54 UTC, JohnAgapeyev requested changes
We don't appreciate tabs 'round these parts

2017-03-16 02:21 UTC, JohnAgapeyev requested changes

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Node.h
> +    virtual ~Node() {} // default dtor
Destructor should be marked as default

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Node.h
> +         lv += (dir%2 ==0 ? BASE_COST : EXTEND_COST);
Spacing on the % operator

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Node.h
> +        yDist = yDest - yPos;
Assignment should be done on the same line as the declaration here

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Node.h
> +        return (static_cast<int>(sqrt(xDist * xDist + yDist * yDist)));
Remove very outer set of () that wrap the static cast
They are unnecessary

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
>  void Zombie::collidingProjectile(int damage) {
Make param const

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +    return (ch.detectMovementCollision(this));
Can be condensed to `return GameManager::instance()->getCollisionHandler().detectMovementCollision(this);`

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +    int yNodeDest = static_cast<int>(yDest / TILE_SIZE);
Make these variables const

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +            if (!(xdx < 0 || xdx > COL -1 || ydy < 0 || ydy > ROW - 1
Spacing on `COL -1`

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +                    dirMap[xdx][ydy] = (i + DIR_CAP/2)%DIR_CAP;
Spacing

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +                    dirMap[xdx][ydy] = (i + DIR_CAP/2)%DIR_CAP;
More Spacing

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +bool Zombie::checkBounds(const float x, const float y) const {
Make method constexpr since it can be made as such

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Zombie.h
> +enum ZombieDirections {
Change enum to enum class

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Zombie.h
> +enum ZombieAngles {
Enum class

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Zombie.h
> +static constexpr float OVERLAP = 0.1f;
'f' is not needed when variable is defined as float
Either declare it as auto, or remove the f

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Zombie.h
> +enum ZombieState{
Enum class

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/creeps/Zombie.h
> +    void setState(const ZombieState state_) {
Rename param to not use underscore

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/game/GameManager.cpp
> +            z.second.move((z.second.getDX()*delta), (z.second.getDY()*delta), collisionHandler);
Spacing on the multiplication

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/game/GameManager.cpp
> +    zombieManager.at(id).generatePath(x, y, MAP_WIDTH/2 - BASE_WIDTH, MAP_HEIGHT/2 - BASE_HEIGHT);
Spacing on the divide

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/game/GameManager.h
> +    const std::map<int32_t, Zombie>& GameManager::getZombies() {
change return type to const auto&

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/game/GameStateMatch.cpp
> +        level(),  base(), camera(gameWidth,gameHeight) {
Do these empty initializers need to be here?
Can't you just leave them out and the compiler will automatically call them?

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/game/GameStateMatch.h
> +static constexpr float TICK_SEC = 1000.f;
remove .f

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/turrets/Turret.cpp
> +    {
Bracket should be on the same line as the loop

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/turrets/Turret.cpp
> +        float zombieY = zombie.getY();
Make const

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/turrets/Turret.cpp
> +        yDelta *= yDelta;
I'd rather you move these squaring multiplies into the below sqrt call and make the floats defined as const than do this here

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/turrets/Turret.cpp
> +    float deltaY = getY() - target->second.getY();
Needs const

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/turrets/Turret.cpp
> +    double angle = ((atan2(deltaX, deltaY) * 180.0) / M_PI) * -1;
Should either be const, or calculated inline inside the call to setAngle

2017-03-16 02:21 UTC, JohnAgapeyev commented on src/turrets/Turret.cpp
> +float Turret::getRange() const {
Move to header

2017-03-16 05:21 UTC, RobertArendac commented on src/creeps/Zombie.cpp
> +bool Zombie::checkBounds(const float x, const float y) const {
Wouldn't compile, Zombie has non-trivial destructor

2017-03-16 16:28 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +bool Zombie::checkBounds(const float x, const float y) const {
Then make it static
This method doesn't refer to any members of zombie, so it can be static
static constexpr method should hopefully fix things

2017-03-16 17:42 UTC, JohnAgapeyev commented on src/creeps/Node.h
> +    } // default dtor
This isn't what I meant when I said mark it as default
But you've added code to the destructor so it's not required
FYI what I was referring to was `virtual ~Node() = default;`
It's better than having an empty destructor that does nothing

2017-03-16 18:04 UTC, JohnAgapeyev requested changes
Small tweaks still needed

2017-03-16 18:04 UTC, JohnAgapeyev commented on src/creeps/Node.h
> +        int xDist = xDest - xPos, yDist = yDest - yPos;
This looks gross.
Split the declaration of xDist and yDist onto separate lines

2017-03-16 18:04 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +    if (state != ZombieState::ZOMBIE_MOVE) {
If statement is not required
If the zombie isn't in a move state, it is now in a move state
If the zombie is in a move state, it is now in a move state
So we can remove a branch and always set the zombies state to moving

2017-03-16 18:04 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +    int x, y, xdx, ydy;
Prefer separate lines for multiple variable declarations

2017-03-16 18:04 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +    static priority_queue<Node> pq[2];
This is  a 1D array
So use std::array

2017-03-16 18:04 UTC, JohnAgapeyev commented on src/creeps/Zombie.cpp
> +                path = c + path;
'c' is only ever used and assigned in this loop
It's not necessary, so remove c and replace with its value in this line

2017-03-16 18:04 UTC, JohnAgapeyev commented on src/creeps/Zombie.h
> +    bool checkTarget();               // checks if the zombie already arrived at the target
This and isMoving should be const methods

2017-03-16 18:04 UTC, JohnAgapeyev commented on src/game/GameManager.h
> +    const auto& getZombies() {
Remove const here
I screwed up saying it should be const
I'm assuming you'd want to be able to change the contents of zombie manager through this getter

2017-03-16 18:04 UTC, JohnAgapeyev commented on src/turrets/Turret.cpp
> +        const float distance = sqrt(pow(xDelta, 2) + pow(yDelta, 2));
Don't use `pow` method for this
It's used for arbitrary exponentiation
For simple squaring, doing `xDelta * xDelta` is faster

2017-03-16 18:04 UTC, JohnAgapeyev commented on src/turrets/Turret.cpp
> +    // TODO: Attack a zombie;
TODO should not be put into main repo

2017-03-16 18:45 UTC, JohnAgapeyev approved these changes

2017-03-16 18:46 UTC, merged