Stores stores stores!
bcit-datacomm/4981_Linux_Game pull request #32
Opened 2017-03-31 06:41 UTC by Uitiam

WeaponStore and DropPoints are in. Weapon Store Spawns a random Weapon on a DropPoint when a player presses 'E' near it. DropPoints are in Top Left corner... You wont miss the store :taco: aslo fixed issue #30

2017-03-31 14:59 UTC, isaacmorneau commented
Woah woah woah, 🌮 is John's. You need a different one

2017-03-31 15:31 UTC, JohnAgapeyev requested changes
I'm constantly plagued by constant troubles
Taco time has not yet begun
Please review

2017-03-31 15:31 UTC, JohnAgapeyev commented on src/buildings/DropPoint.cpp
> +DropPoint::~DropPoint(){
Destructor should be marked as default in the header if it is not used

2017-03-31 15:31 UTC, JohnAgapeyev commented on src/buildings/WeaponStore.cpp
> +int32_t WeaponStore::purchase(int num){
const

2017-03-31 15:31 UTC, JohnAgapeyev commented on src/buildings/WeaponStore.cpp
> +        int32_t weaponId = createWeapon(num);
CONST

2017-03-31 15:31 UTC, JohnAgapeyev commented on src/buildings/WeaponStore.cpp
> +        float y = dp.getCoord().second;
A CONST A CONST
MY WORLD FOR A CONST

2017-03-31 15:31 UTC, JohnAgapeyev commented on src/buildings/WeaponStore.cpp
> +            gm->addWeapon(std::dynamic_pointer_cast<Weapon>(std::make_shared<Rifle>(r)));
Use make the rifle inline and wrap the line
I don't care about a temp var named r.

2017-03-31 15:31 UTC, JohnAgapeyev commented on src/buildings/WeaponStore.cpp
> +            break;
Return and break?
One of these things are not like the other
One of these things must die alone

2017-03-31 15:31 UTC, JohnAgapeyev commented on src/game/GameManager.cpp
> +            createDropPoint(coordX + (200*i), coordY + (200*j));
200 is a magic number

2017-03-31 15:31 UTC, JohnAgapeyev commented on src/player/Marine.cpp
> +#include <stdlib.h>
cstdlib

2017-03-31 16:04 UTC, isaacmorneau requested changes
mostly const tbh

2017-03-31 16:04 UTC, isaacmorneau commented on src/basic/Entity.cpp
> +            logv("Store x: %d y: %d\n", pickupSize.x, pickupSize.y);
this is not specific to entities and as such should not be in entities

2017-03-31 16:04 UTC, isaacmorneau commented on src/buildings/DropPoint.h
> +    int32_t getID()const{return id;};//maitiu March 21
Class A spacing issue

2017-03-31 16:04 UTC, isaacmorneau commented on src/buildings/Object.cpp
> +    //updateRectHitBoxes();
🔥 🔥 AAAAH! 🔥 

mostly why?

2017-03-31 16:04 UTC, isaacmorneau commented on src/buildings/Store.h
> +    Store(int32_t id, const SDL_Rect dest, const SDL_Rect pickupSize);
const id bruv

2017-03-31 16:04 UTC, isaacmorneau commented on src/buildings/Store.h
> +    virtual int32_t purchase(int num);//creates item and item drop for user
cnast sconst const smcaaaaa

const

2017-03-31 16:04 UTC, isaacmorneau commented on src/buildings/WeaponStore.cpp
> +WeaponStore::WeaponStore(int32_t id, const SDL_Rect dest, const SDL_Rect pickupSize): Store(id, dest, pickupSize){
const

2017-03-31 16:04 UTC, isaacmorneau commented on src/buildings/WeaponStore.cpp
> +    return 0;
why does this just return 0? no comment, i dont know what this is for

2017-03-31 16:04 UTC, isaacmorneau commented on src/buildings/WeaponStore.cpp
> +    int32_t id = gm->generateID();
const

2017-03-31 16:04 UTC, isaacmorneau commented on src/buildings/WeaponStore.cpp
> +        case 2:
magic numbers are a no no

2017-03-31 16:04 UTC, isaacmorneau commented on src/buildings/WeaponStore.h
> +    WeaponStore(int32_t id, const SDL_Rect dest, const SDL_Rect pickupSize);
const

2017-03-31 16:04 UTC, isaacmorneau commented on src/buildings/WeaponStore.h
> +    int32_t createWeapon(int num);
const and purchase const

2017-03-31 16:04 UTC, isaacmorneau commented on src/buildings/WeaponStore.h
> +private:
useless flag

2017-03-31 16:04 UTC, isaacmorneau commented on src/collision/CollisionHandler.cpp
> +        quadtreeWall(0, {0,0,2000,2000}), quadtreePickUp(0, {0,0,2000,2000}), quadtreeObj(0, {0,0,2000,2000}), quadtreeStore(0,{0,0,2000,2000}) {
lines too long

2017-03-31 16:04 UTC, isaacmorneau commented on src/game/GameManager.cpp
> +    int32_t id = generateID();
const

2017-03-31 16:04 UTC, isaacmorneau commented on src/game/GameManager.cpp
> +    SDL_Rect pickRect = {static_cast<int>(x) - 25,static_cast<int>(y) - 25, 450, 450};
magic numbers

2017-03-31 16:04 UTC, isaacmorneau commented on src/game/GameManager.cpp
> + void GameManager::addStore(int32_t id ,std::shared_ptr<Store> store){
const

2017-03-31 16:04 UTC, isaacmorneau commented on src/game/GameManager.cpp
> +void GameManager::createDropZone(float x, float y, int num){
const

2017-03-31 16:04 UTC, isaacmorneau commented on src/game/GameManager.cpp
> +            createDropPoint(coordX + (200*i), coordY + (200*j));
magic numbers

2017-03-31 16:04 UTC, isaacmorneau commented on src/game/GameManager.cpp
> +     int32_t id = openDropPoints.back();
const

2017-03-31 16:04 UTC, isaacmorneau commented on src/game/GameManager.h
>      void setBoundary(const float startX, const float startY, const float endX, const float endY); // place walls for the boundaries
line length

2017-03-31 16:04 UTC, isaacmorneau commented on src/game/GameManager.h
> +    void addStore(int32_t id, std::shared_ptr<Store> store);//adds store to sotreManager
const

2017-03-31 16:04 UTC, isaacmorneau commented on src/game/GameStateMatch.cpp
> +    GameManager::instance()->createDropZone(100 ,100, 2);
AAAH MAGIC 🔮

2017-03-31 16:04 UTC, isaacmorneau commented on src/inventory/Drop.cpp
> +Drop::Drop(int32_t id, const SDL_Rect &dest, const SDL_Rect &pickupSize): Entity(id, dest, dest, pickupSize){
const

2017-03-31 16:04 UTC, isaacmorneau commented on src/inventory/Drop.h
> +    int32_t dropPoint = -1;
defaults in ctor

2017-03-31 16:04 UTC, isaacmorneau commented on src/inventory/weapons/Weapon.h
>      int32_t getID()const{return wID;};
spacing

2017-03-31 16:04 UTC, isaacmorneau commented on src/player/Marine.cpp
> +    GameManager *gm = GameManager::instance();
const

2017-03-31 18:30 UTC, JohnAgapeyev requested changes

2017-03-31 18:30 UTC, JohnAgapeyev commented on src/buildings/Store.cpp
> +        Object(id, dest, dest, pickupSize, 400, 400, 0){
400 is a magic number 🎇

2017-03-31 18:30 UTC, JohnAgapeyev commented on src/buildings/WeaponStore.cpp
> +        {
Case scoping is no longer required

2017-03-31 18:30 UTC, JohnAgapeyev commented on src/buildings/WeaponStore.cpp
> +            gm->addWeapon(std::dynamic_pointer_cast<Weapon>(std::make_shared<ShotGun>(ShotGun(id))));
You don't need to construct a Shotgun object inside made_shared
Just use id and it will call the constructor with that as a param

2017-03-31 18:30 UTC, JohnAgapeyev commented on src/game/GameManager.cpp
> +    SDL_Rect pickRect = {static_cast<int>(x) - storePickupSize/2 ,static_cast<int>(y) - storePickupSize/2, storeSize + storePickupSize, storeSize + storePickupSize};
Such a long line
It's practically disneyworld

2017-03-31 18:30 UTC, JohnAgapeyev commented on src/game/GameManager.cpp
> +    addStore(id, std::dynamic_pointer_cast<Store>(std::make_shared<WeaponStore>(ws)));
Move weapon store creation inline

2017-03-31 18:30 UTC, JohnAgapeyev commented on src/game/GameManager.cpp
> +     dropPointManager.emplace(id, dp);
Move drop point object creation inline

2017-03-31 18:30 UTC, JohnAgapeyev commented on src/game/GameManager.h
> +    int storePickupSize = 50;
Defaults go in the constructor

2017-03-31 18:30 UTC, JohnAgapeyev commented on src/game/GameStateMatch.cpp
> +    GameManager::instance()->createDropZone(100 ,100, 4);
I want these mothafuqin magic numbers outta this mothafuqin code

2017-03-31 23:30 UTC, isaacmorneau requested changes

2017-03-31 23:30 UTC, isaacmorneau commented on src/game/GameManager.h
> +    int storePickupSize;
these should never be member variables
follow the implementation guide on how to create constants

2017-03-31 23:30 UTC, isaacmorneau commented on src/game/GameStateMatch.cpp
> +    GameManager::instance()->createDropZone(dropZoneX , dropZoneY, dropZoneSize);
this is not a solution use `static constexpr int` these are constants not variables!

2017-04-01 00:55 UTC, JohnAgapeyev approved these changes

2017-04-01 03:15 UTC, isaacmorneau approved these changes

2017-04-01 03:16 UTC, merged