adding character animation and updating sprite sheets
bcit-datacomm/4981_Linux_Game pull request #33
Opened 2017-03-31 08:12 UTC by CerberusOne

2017-03-31 13:49 UTC, eyyu commented on src/game/GameStateMatch.cpp
> +    player.getMarine()->setSrcRect(0, 0, 75, 125);
Im not a fan of magic numbers,
you can use `static constexpr int NAME = value;`/ Check out Player.h for an example.

2017-03-31 13:53 UTC, eyyu requested changes
Just some magic number issues to resolve please.

2017-03-31 13:53 UTC, eyyu commented on src/player/Marine.cpp
> +    setSrcRect(Entity::getSpritePosX(), Entity::getSpritePosY(), 75, 125); //update image
Same magic nums

2017-03-31 13:53 UTC, eyyu commented on src/player/Marine.cpp
> +        setSrcRect(SPRITE_SIZE_X*4, SPRITE_SIZE_Y*7, 110, 100); //testing dead state (change to when HP == 0)
and magic nums here; comment says "testing" ... does that mean this will change?

2017-03-31 13:53 UTC, eyyu commented on src/player/Marine.h
> +#define SPRITE_SIZE_X 75 //width of any marine image
I found em! 
its defined here! please use them!

2017-03-31 14:57 UTC, isaacmorneau requested changes

2017-03-31 14:57 UTC, isaacmorneau commented on src/basic/Entity.h
> +    int spritePosY;
I see no point in these, why not modify the src rect directly instead of adding an extra step?

2017-03-31 14:57 UTC, isaacmorneau commented on src/player/Marine.cpp
> +    double radians = (angle -90) * M_PI/180;
Should be const

2017-03-31 14:57 UTC, isaacmorneau commented on src/player/Marine.cpp
> +    setSrcRect(Entity::getSpritePosX(), Entity::getSpritePosY(), 75, 125); //update image
All these should be `static constexpr double` and indentation violates style guide

2017-03-31 14:57 UTC, isaacmorneau commented on src/player/Marine.cpp
> +        else if ((int)frameCount % FRAME_COUNT_WALK == 0) {
This indentation actually managed to follow none of any other accepted styles
Take a look at the examples please

2017-03-31 14:58 UTC, isaacmorneau commented on src/player/Marine.cpp
> +    setSrcRect(Entity::getSpritePosX(), Entity::getSpritePosY(), 75, 125); //update image
When I say these I mean the magic rotational numbers

2017-03-31 15:37 UTC, JohnAgapeyev requested changes

2017-03-31 15:37 UTC, JohnAgapeyev commented on src/basic/Entity.cpp
> +int Entity::getSpritePosY() {
Trivial getters go in the header
Also should be const

2017-03-31 15:37 UTC, JohnAgapeyev commented on src/basic/Entity.cpp
> +void Entity::setSpritePosY(int y) {
Args need const
And should be in the header

2017-03-31 15:37 UTC, JohnAgapeyev commented on src/player/Marine.cpp
> +    else if (radians > -3*M_PI/8 && radians < -M_PI/8) {
Else should be on the same line as closing braces
Follow the style guide

2017-03-31 15:37 UTC, JohnAgapeyev commented on src/player/Marine.cpp
> +    else if (radians > -9*M_PI/8 && radians < -7*M_PI/8) {
Magic numbers may produce wonder and amazement, but I am not a fan of magic shows
Please fix

2017-04-01 03:24 UTC, JohnAgapeyev requested changes

2017-04-01 03:24 UTC, JohnAgapeyev commented on src/player/Marine.cpp
> +        } else if ((int)frameCount % FRAME_COUNT_WALK == 0) {
Don't use C-style casts
Read the implementation guide

2017-04-01 03:24 UTC, JohnAgapeyev commented on src/player/Marine.h
> +static constexpr double SPRITE_ANGLE8 = 3*M_PI/8;
It's so tight in there
Those values need some spacing

2017-04-01 03:26 UTC, isaacmorneau approved these changes
as john will say, no c style casts but other than that looks good

2017-04-01 03:27 UTC, isaacmorneau requested changes
Just realized that this now has merge conflicts as of the last merge.

please fix

2017-04-01 23:46 UTC, JohnAgapeyev approved these changes

2017-04-01 23:46 UTC, JohnAgapeyev commented on src/player/Marine.cpp
> +    const double radians = (getAngle() -90) * M_PI/180;
Spacing

2017-04-03 16:57 UTC, isaacmorneau requested changes

2017-04-03 16:57 UTC, isaacmorneau commented on src/game/GameStateMatch.cpp
> +void GameStateMatch::handle(unsigned long countedFrames) {
const

2017-04-03 16:57 UTC, isaacmorneau commented on src/game/GameStateMatch.cpp
> +void GameStateMatch::handle(unsigned long countedFrames) {
also why are you counting frames in a double (its already in the timer) and then casting it to a long?
that is really really bad. instead you should be taking in the stepTimer.getTicks() as whatever type it returns

2017-04-03 16:57 UTC, isaacmorneau commented on src/game/GameStateMenu.h
> +    virtual void handle(unsigned long countedFrames) override;
const as well

2017-04-03 16:57 UTC, isaacmorneau commented on src/player/Marine.cpp
> +void Marine::updateImageWalk(const Uint8 *state, double frameCount) {
const also frame should be the same type as the getTicks return as that should be what its receiving

2017-04-04 02:38 UTC, isaacmorneau approved these changes

2017-04-04 02:43 UTC, eyyu approved these changes

2017-04-04 02:43 UTC, merged