Zombiehands
bcit-datacomm/4981_Linux_Game pull request #34
Opened 2017-03-31 18:45 UTC by MTattrie

added inventory to zombie, and method for zombie attack
added melee attack collision handler 
added weapon zombiehand
handle turret and barricades health reaching 0

TODO
apply firerate to zombies (need to talk to rob about zombie attack state)
add zombie attack detection for the base (object manager, base id is always 0?)
handle Marine death (issue)
*camera is currently tied to a marine

2017-04-01 00:25 UTC, isaacmorneau requested changes

2017-04-01 00:25 UTC, isaacmorneau commented on src/creeps/Zombie.cpp
> +    if( w != nullptr){
just `if (w) {` is fine

2017-04-01 00:25 UTC, isaacmorneau commented on src/inventory/Inventory.cpp
> +Inventory::Inventory(): defaultGun(GameManager::instance()->generateID()), tempZombieHand(GameManager::instance()->generateID()) {
wrap line

2017-04-01 00:25 UTC, isaacmorneau commented on src/inventory/weapons/MeleeWeapon.cpp
> +: Weapon(type, sprite, fireSound, hitSound, reloadSound, emptySound, range, damage, AOE,
spacing

2017-04-01 00:25 UTC, isaacmorneau commented on src/inventory/weapons/MeleeWeapon.cpp
> +    for(auto& z: hitTurrets){//update each zombie's helth
i think all preceding for s can be `const auto&` no?

2017-04-01 00:25 UTC, isaacmorneau commented on src/inventory/weapons/MeleeWeapon.h
> +            int clipMax, int ammo, int reloadDelay, int fireDelay, int32_t id);
const parameters

2017-04-01 00:59 UTC, JohnAgapeyev requested changes

2017-04-01 00:59 UTC, JohnAgapeyev commented on src/collision/CollisionHandler.cpp
> +std::vector<Entity *> CollisionHandler::detectMeleeCollision(std::vector<Entity*> returnObjects, const Entity *entity, const HitBox hb){
Wrap it up

2017-04-01 00:59 UTC, JohnAgapeyev commented on src/collision/CollisionHandler.cpp
> +            && SDL_HasIntersection(&hb.getRect(), &obj->getDamHitBox().getRect())){
Fix indentation

2017-04-01 00:59 UTC, JohnAgapeyev commented on src/inventory/weapons/MeleeWeapon.cpp
> +    std::vector<Entity *> hitBarricades;
Variables should be declared near where they are used
In this case, move these declarations down to include their assignments further down

2017-04-04 00:50 UTC, JohnAgapeyev commented
You've got merge conflicts yo

2017-04-04 01:51 UTC, isaacmorneau requested changes

2017-04-04 01:51 UTC, isaacmorneau commented on src/inventory/weapons/MeleeWeapon.cpp
> +        int fireDelay, int32_t id)
The rest of the should be const as well

2017-04-04 01:51 UTC, isaacmorneau commented on src/collision/CollisionHandler.cpp
> +        if (obj != nullptr && entity != obj
`if (obj && ...` no need for nullptr check

2017-04-04 01:51 UTC, isaacmorneau commented on src/inventory/weapons/MeleeWeapon.cpp
> +        int damage, int AOE, int penetration, int clip, int clipMax, int ammo, int reloadDelay,
the rest of the params should also be const

2017-04-04 01:51 UTC, isaacmorneau commented on src/inventory/weapons/ZombieHand.h
> +}
these are variables that shouldnt change but please avoid space aligning like this as per the guide

2017-04-04 01:51 UTC, isaacmorneau commented on src/inventory/weapons/ZombieHand.h
> +    ZombieHand(int32_t id);
const

2017-04-04 01:51 UTC, isaacmorneau commented on src/player/Marine.cpp
> +    */
is this supposed to be commented?

2017-04-04 01:51 UTC, isaacmorneau commented on src/turrets/Turret.cpp
> +    }
i ask about marine because this remove is in

2017-04-04 14:11 UTC, eyyu approved these changes

2017-04-04 14:56 UTC, JohnAgapeyev approved these changes
A couple lines need condensing, but otherwise fine

2017-04-04 14:56 UTC, JohnAgapeyev commented on src/inventory/weapons/MeleeWeapon.cpp
> +    hitMarines = ch.detectMeleeCollision(ch.getQuadTreeEntities(ch.quadtreeMarine, &mov),&mov, hitBox);
Declaration and initialization can be done on the same line

2017-04-04 18:13 UTC, isaacmorneau approved these changes

2017-04-04 18:14 UTC, isaacmorneau commented
once merge conflicts are fixed its good

2017-04-04 18:42 UTC, merged