Refactoring to follow style guide
bcit-datacomm/4981_Linux_Game pull request #41
Opened 2017-04-04 17:53 UTC by Yiaoping

List of folders refactored

audio
creeps
turrets
basic
main.cpp

2017-04-04 18:47 UTC, isaacmorneau requested changes
merge conflicts

2017-04-04 18:47 UTC, isaacmorneau commented on src/audio/AudioManager.h
> +    chunkMap  mapChunk;
[hungarian notation is forbidden](https://github.com/bcit-datacomm/4981_Linux_Game/wiki/Style-Guide#variable-naming) you can just call it `music` and `chunks`

2017-04-04 21:05 UTC, JohnAgapeyev approved these changes

2017-04-04 21:05 UTC, JohnAgapeyev commented on src/basic/LTimer.cpp
> +        if ( mPaused ) {
You spaces between code and parentheses
Should be `if (mPaused) {`

2017-04-05 01:52 UTC, isaacmorneau approved these changes

2017-04-05 02:02 UTC, merged