Feature/turret shooting
bcit-datacomm/4981_Linux_Game pull request #66
Opened 2017-04-05 20:14 UTC by YiHChen

- Turrets now have an inventory
- Inventory is given a unique 'turretGun' upon creation 
- turretGun currently only has 10 shots (not sure about these stats at the moment, will most likely change)
-Upon reaching 0 ammo, turret is automatically destroyed.

2017-04-05 20:21 UTC, JohnAgapeyev requested changes

2017-04-05 20:21 UTC, JohnAgapeyev commented on src/game/GameManager.cpp
> +    //assert(w.second);
No,
A thousand times no
Why did you remove a perfectly good assert?
No

2017-04-05 20:21 UTC, JohnAgapeyev commented on src/inventory/weapons/TurretGun.h
> +    constexpr int FIREDELAY     = 1500;
This is  some nasty spacing

2017-04-05 20:21 UTC, JohnAgapeyev commented on src/turrets/Turret.cpp
> +    if (w != nullptr) {
`if (w) {`

2017-04-05 20:21 UTC, JohnAgapeyev commented on src/turrets/Turret.h
> +    Inventory inventory;
You made a public member
John no likey public members
Fix this

2017-04-05 21:15 UTC, JohnAgapeyev approved these changes

2017-04-06 02:59 UTC, isaacmorneau requested changes

2017-04-06 02:59 UTC, isaacmorneau commented on src/inventory/weapons/TurretGun.h
> +using std::string;
while this is valid and should be ok, avoid all usings in headers. it is kinder to people including the files to not have namespace lookups they dont want.

2017-04-06 02:59 UTC, isaacmorneau commented on src/turrets/Turret.cpp
> + * Programmer: Mark Chen, Micheal Goll, Jacob McPhail, Isaac Morneau, Maitiu Morton, Mark Tattrie
um, really? did we all work on this?

2017-04-06 02:59 UTC, isaacmorneau commented on src/turrets/Turret.h
> +    Inventory getInventory() {return inventory;};
should be a reference

2017-04-07 01:49 UTC, isaacmorneau approved these changes

2017-04-07 01:50 UTC, isaacmorneau commented
merge conflicts

2017-04-07 02:13 UTC, merged