Medkit
bcit-datacomm/4981_Linux_Game pull request #97
Opened 2017-04-10 16:45 UTC by mgoerwell

The basic medkit will now heal the player to full health.

2017-04-10 17:39 UTC, isaacmorneau requested changes

2017-04-10 17:39 UTC, isaacmorneau commented on src/game/GameStateMatch.cpp
> +                            GameManager::instance()->getPlayer().getMarine()->setHealth(50);
k should still kill the player

2017-04-10 17:39 UTC, isaacmorneau commented on src/inventory/BasicMedkit.cpp
> +	x.setHealth(100);
instead of the magic number it should use the health constant in marine

2017-04-10 17:39 UTC, isaacmorneau commented on src/player/Player.cpp
> +        marine->inventory.useItem(*marine);
this needs to make sure that marine is not nullptr

2017-04-10 17:39 UTC, isaacmorneau commented on src/inventory/BasicMedkit.cpp
> +	marine.setHealth(100);
this also needs to use the marine constants

2017-04-10 17:43 UTC, JohnAgapeyev approved these changes

2017-04-11 05:35 UTC, isaacmorneau approved these changes

2017-04-11 05:35 UTC, merged